apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      chart: podinfo # Must be the same as the upstream chart name
      version: 6.1.5 # Pin to semver major versions to avoid breaking changes but still get bugfixes/updates
      sourceRef:
        kind: HelmRepository
        name: podinfo # References the HelmRepository you created earlier
        namespace: flux-system # All HelmRepositories exist in the flux-system namespace
  interval: 15m
  timeout: 5m
  releaseName: podinfo # _may_ be different from the upstream chart name, but could cause confusion
  valuesFrom:
  - kind: ConfigMap
    name: podinfo-helm-chart-value-overrides # Align with the name of the ConfigMap containing all values
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity

