apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: snipeit-db
  name: snipeit-db
  namespace: snipeit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: snipeit-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: snipeit-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: snipeit
            - name: MYSQL_PASSWORD
              value: soasdlfkjasdfhasdlfkjchangeme
            - name: MYSQL_ROOT_PASSWORD
              value: laksjdfasdlfkhjasdfkihasdf111kjasdflkjasdf
            - name: MYSQL_USER
              value: snipeit
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Europe/Vienna
          image: lscr.io/linuxserver/mariadb:latest
          name: snipeit-db
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: snipeit-db-claim0
      restartPolicy: Always
      volumes:
        - name: snipeit-db-claim0
          persistentVolumeClaim:
            claimName: snipeit-db-claim0
status: {}
