apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
    metallb.universe.tf/loadBalancerIPs: 172.16.120.210
  creationTimestamp: null
  labels:
    io.kompose.service: taskd
  name: taskd
  namespace: taskwarrior
spec:
  ports:
    - name: "53589"
      port: 53589
      targetPort: 53589
  selector:
    io.kompose.service: taskd
  type: LoadBalancer
